### ISSUE TITLE
command line not recognizing command

### ISSUE THREAD

**Issue by incendor** [jsoma/tesseract-uzn#1]
Hi!

Following your installation instructions I put tesseract-uzn in /usr/local/bin/ but when I try to use it, no matter from which directory, I get "command not found".

Did I miss something?

OS is Linux Mint 18.2 Sonya with Cinnamon 3.4.3

Thanks in advance!

**Comment by jsoma** [comment]
Hmmm, there are a few different things that *could* be a problem, let's just go through the laundry list.

**`/usr/local/bin` might not be in your PATH:**

Can you run `echo $PATH` and make sure `/usr/local/bin` is one of the entries?

**`tesseract` needed a shebang, maybe?:**

I updated the code, could you re-download and copy the new version to `/usr/local/bin`?

**`tesseract` isn't in your PATH:**

Can you run `which tesseract` and make sure it returns something? If not, move tesseract into `/usr/local/bin`, too.

**`tesseract-uzn` isn't executable**

Maybe it isn't actually an executable file yet, for some reason. `chmod u+x /usr/local/bin/tesseract-uzn`, then try running it again.

 **`tesseract-uzn` didn't successfully make it into `/usr/local/bin`**

Can you run `which tesseract-uzn` to see if something shows up?

**Comment by incendor** [comment]
I tested all your suggestions, results below. Before you look at those, I want to inform you that I changed the actual tesseract command in your code to do this:

`tesseract "$image_tmp" "$txt_target" -psm 4 -l eng+Beleren+Goudy+matrixbold`

Adding `-l traineddata-files` enables tesseract to user multiple traineddata files if you want to add additional charsets, languages or fonts to recognition. As far as I understood your work, this shouldn't mess it up in any way.


So... here's the Results:

**Can you run echo $PATH and make sure /usr/local/bin is one of the entries?**
```
mint@mint-VirtualBox ~ $ echo $PATH
/home/mint/bin:/home/mint/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**I updated the code, could you re-download and copy the new version to /usr/local/bin?**
I downloaded the latest version just today (right before posting). Did you insert changes since then?

**Can you run which tesseract and make sure it returns something?**
```
mint@mint-VirtualBox ~ $ which tesseract
/usr/bin/tesseract
```

**Maybe it isn't actually an executable file yet, for some reason. chmod u+x /usr/local/bin/tesseract-uzn, then try running it again.**
```
mint@mint-VirtualBox ~ $ sudo tesseract-uzn /home/mint/TessOCR/test.uzn /home/mint/TessOCR/test.tiff 
/usr/local/bin/tesseract-uzn: 11: /usr/local/bin/tesseract-uzn: Bad substitution
```

**Can you run which tesseract-uzn to see if something shows up?**
`mint@mint-VirtualBox ~ $ which tesseract-uzn
`
**BUT**
```
mint@mint-VirtualBox ~ $ ls /usr/local/bin/
apt  gnome-help  highlight  mint-sha256sum  search  tesseract-uzn  yelp
```

Edit: corrected code formatting

**Comment by incendor** [comment]
OK, I got it to run by adding `#!/bin/bash` as suggested here: [Stackoverflow](https://stackoverflow.com/a/36434146)

Now I have:

```
mint@mint-VirtualBox ~ $ sudo tesseract-uzn /home/mint/TessOCR/test.uzn /home/mint/TessOCR/test.tiff
Processing /home/mint/TessOCR/test.tiff
Processing in /tmp/tmp.TKBSvIO1dk
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Error during processing.
```

...and looking into the code I notice that the tesseract execution uses `"$txt_target"` for writing the result. I'm not quite sure how to pass the output file when calling the script.

**Comment by jsoma** [comment]
Just pushed a lot of new stuff - cleaned up some of the filename/path handling and including some tests. Can you download and give it a shot by running `./test.sh`? It will test running it on a few files in a subdirectory. Hopefully we'll be good to go!

**Comment by incendor** [comment]
Yeah, now everything works as expected!

Maybe I'll modify it a bit to accept an output file parameter and a way to configure different traineddata files to use... :)

Thank you very much for your quick and competent help!
